# Data Inspection

In [40]:
# Import Libraries

import pandas as pd
import numpy as np

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [5]:
# Load Dataset

df = pd.read_csv("used_cars_dataset_v2.csv")

# Display first 5 rows
df.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"

In [9]:
# Basic Dataset Information

print("Dataset Shape:")
print("-"*50)
print(df.shape)

print("\n")

print("Dataset Information")
print("-"*50)
print(df.info())

print("\n")

print("Statistical Summary")
print("-"*50)
print(df.describe(include="all").T)

Dataset Shape:
--------------------------------------------------
(14993, 11)


Dataset Information
--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 14993 entries, 0 to 14992
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         14993 non-null  str
 1   model         14993 non-null  str
 2   Year          14993 non-null  int64
 3   Age           14993 non-null  int64
 4   kmDriven      14905 non-null  str
 5   Transmission  14993 non-null  str
 6   Owner         14993 non-null  str
 7   FuelType      14993 non-null  str
 8   PostedDate    14993 non-null  str
 9   AdditionInfo  14993 non-null  str
 10  AskPrice      14993 non-null  str
dtypes: int64(2), str(9)
memory usage: 1.3 MB
None


Statistical Summary
--------------------------------------------------
                count unique                                             top  \
Brand           14993     43                                   Maruti Suzuki
model           14993    436                                         Wagon-R
Year          14993.0    NaN                                             NaN
Age           14993.0    NaN                                             NaN
kmDriven        14905   2718                                       65,000 km
Transmission    14993      2                                       Automatic
Owner           14993      2                                          second
FuelType        14993      4                                          Petrol
PostedDate      14993     13                                          Nov-24
AdditionInfo    14993  10676  BMW 3 Series GT 320d Luxury Line, 2015, Diesel
AskPrice        14993   1616                                      ₹ 4,50,000

               freq        mean       std     min     25%     50%     75%  \
Brand          4615         NaN       NaN     NaN     NaN     NaN     NaN
model           616         NaN       NaN     NaN     NaN     NaN     NaN
Year            NaN  2016.32215  4.343017  1900.0  2014.0  2017.0  2019.0
Age             NaN     7.67785  4.343017     0.0     5.0     7.0    10.0
kmDriven        295         NaN       NaN     NaN     NaN     NaN     NaN
Transmission   7618         NaN       NaN     NaN     NaN     NaN     NaN
Owner          7794         NaN       NaN     NaN     NaN     NaN     NaN
FuelType       5822         NaN       NaN     NaN     NaN     NaN     NaN
PostedDate    13251         NaN       NaN     NaN     NaN     NaN     NaN
AdditionInfo     30         NaN       NaN     NaN     NaN     NaN     NaN
AskPrice        221         NaN       NaN     NaN     NaN     NaN     NaN

                 max
Brand            NaN
model            NaN
Year          2024.0
Age            124.0
kmDriven         NaN
Transmission     NaN
Owner            NaN
FuelType         NaN
PostedDate       NaN
AdditionInfo     NaN
AskPrice         NaN

In [10]:
# Missing Values

missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum()/len(df))*100
})

missing = missing.sort_values(
    by="Missing Percentage",
    ascending=False
)

missing

              Missing Count  Missing Percentage
kmDriven                 88            0.586941
model                     0            0.000000
Brand                     0            0.000000
Year                      0            0.000000
Age                       0            0.000000
Transmission              0            0.000000
Owner                     0            0.000000
FuelType                  0            0.000000
PostedDate                0            0.000000
AdditionInfo              0            0.000000
AskPrice                  0            0.000000

In [15]:
# Duplicate Rows
duplicates = df.duplicated().sum()
print(f"Duplicate Rows : {duplicates}")


# Data Types
print("\n Data Types:")
df.dtypes

Duplicate Rows : 997

 Data Types:

Brand             str
model             str
Year            int64
Age             int64
kmDriven          str
Transmission      str
Owner             str
FuelType          str
PostedDate        str
AdditionInfo      str
AskPrice          str
dtype: object

In [16]:
# Unique Values
print("\n Unique Values:")
unique = pd.DataFrame({
    "Data Type": df.dtypes,
    "Unique Values": df.nunique()
})

unique

 Unique Values:

             Data Type  Unique Values
Brand              str             43
model              str            436
Year             int64             36
Age              int64             36
kmDriven           str           2718
Transmission       str              2
Owner              str              2
FuelType           str              4
PostedDate         str             13
AdditionInfo       str          10676
AskPrice           str           1616

In [20]:
# Sample Values

for column in df.columns:
    print(column)
    print("-"*60)
    print(df[column].dropna().unique()[:10])
    print()

Brand
------------------------------------------------------------
<StringArray>
[        'Honda',        'Toyota',    'Volkswagen', 'Maruti Suzuki',
           'BMW',          'Ford',           'Kia', 'Mercedes-Benz',
       'Hyundai',          'Audi']
Length: 10, dtype: str

model
------------------------------------------------------------
<StringArray>
[               'City',              'Innova',           'VentoTest',
               'Swift',              'Baleno',                  'X3',
            '5 Series', 'maruti-suzuki-dzire',            'Ecosport',
            'Alto-K10']
Length: 10, dtype: str

Year
------------------------------------------------------------
[2001 2009 2010 2017 2019 2014 2020 2018 2021 2012]

Age
------------------------------------------------------------
[23 15 14  7  5 10  4  6  3 12]

kmDriven
------------------------------------------------------------
<StringArray>
[  '98,000 km', '190000.0 km',   '77,246 km',   '83,500 km',   '45,000 km',
   '83,000 km',  '168,000 km',   '25,000 km',   '33,759 km',   '69,713 km']
Length: 10, dtype: str

Transmission
------------------------------------------------------------
<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str

Owner
------------------------------------------------------------
<StringArray>
['second', 'first']
Length: 2, dtype: str

FuelType
------------------------------------------------------------
<StringArray>
['Petrol', 'Diesel', 'Hybrid/CNG', 'hybrid']
Length: 4, dtype: str

PostedDate
------------------------------------------------------------
<StringArray>
['Nov-24', 'Jul-24', 'Oct-24', 'Aug-24', 'Sep-24', 'May-24', 'Jun-24',
 'Apr-24', 'Jan-24', 'Feb-24']
Length: 10, dtype: str

AdditionInfo
------------------------------------------------------------
<StringArray>
['Honda City v teck in mint condition, valid genuine car,',
     'Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, Diesel',
  'Volkswagen Vento 2010-2013 Diesel Breeze, 2010, Diesel',
          'Maruti Suzuki Swift 2017 Diesel Good Condition',
            'Maruti Suzuki Baleno Alpha CVT, 2019, Petrol',
                     'BMW X3 2.0 XDRIVE 20D, 2014, Diesel',
       'Toyota Innova 2.5 VX 8 Seater BS IV, 2014, Diesel',
             'BMW 5 Series 3.0 530D M Sport, 2019, Diesel',
               'Maruti Suzuki Dzire 1.2 VXI, 2020, Petrol',
   'Ford Ecosport 1.5 Ti VCT MT Titanium BE, 2017, Petrol']
Length: 10, dtype: str

AskPrice
------------------------------------------------------------
<StringArray>
[ '₹ 1,95,000',  '₹ 3,75,000',  '₹ 1,84,999',  '₹ 5,65,000',  '₹ 6,85,000',
 '₹ 13,50,000', '₹ 10,25,000', '₹ 59,50,000',  '₹ 6,22,000',  '₹ 6,49,000']
Length: 10, dtype: str

In [26]:
# Inspect Duplicate Rows

duplicates = df[df.duplicated(keep=False)]

print(f"Duplicate Rows (including first occurrence): {duplicates.shape[0]}")

duplicates.head(20)

Duplicate Rows (including first occurrence): 1731

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
5,BMW,X3,2014,10,"83,000 km",Automatic,first,Diesel,Nov-24,"BMW X3 2.0 XDRIVE 20D, 2014, Diesel","₹ 13,50,000"
7,BMW,5 Series,2019,5,"25,000 km",Automatic,second,Diesel,Nov-24,"BMW 5 Series 3.0 530D M Sport, 2019, Diesel","₹ 59,50,000"
8,Maruti Suzuki,maruti-suzuki-dzire,2020,4,"33,759 km",Manual,second,Petrol,Nov-24,"Maruti Suzuki Dzire 1.2 VXI, 2020, Petrol","₹ 6,22,000"
14,Mercedes-Benz,GLE COUPE,2021,3,"32,000 km",Automatic,second,Petrol,Oct-24,Mercedes-Benz GLE COUPE 3.0 53 AMG 4MATIC Plus...,"₹ 1,18,00,000"
19,BMW,3 Series GT,2015,9,"61,000 km",Automatic,second,Diesel,Nov-24,"BMW 3 Series GT 320d Luxury Line, 2015, Diesel","₹ 15,00,000"
20,Ford,Endeavour,2019,5,"77,000 km",Automatic,second,Diesel,Nov-24,"Ford Endeavour 2.2 Titanium AT 4X2, 2019, Diesel","₹ 23,99,000"
23,Audi,A3,2015,9,"42,000 km",Automatic,second,Diesel,Nov-24,"Audi A3 2.0 35 TDI Attraction, 2015, Diesel","₹ 10,50,000"
27,Maruti Suzuki,Celerio,2014,10,"51,000 km",Automatic,second,Petrol,Nov-24,"Maruti Suzuki Celerio 2014-2017 VXI AT, 2014, ...","₹ 3,45,000"
45,Hyundai,Creta,2022,2,30000.0 km,Automatic,second,Petrol,Nov-24,"Hyundai Creta 1.4 SX (O) Turbo Petrol DCT, 202...","₹ 16,90,000"
50,Toyota,Innova Crysta,2018,6,"118,000 km",Automatic,first,Diesel,Nov-24,"Toyota Innova Crysta 2.8Z Automatic, 2018, Diesel","₹ 17,95,000"
54,Hyundai,Creta,2017,7,"70,000 km",Manual,second,Petrol,Nov-24,"Hyundai Creta, 2017, Petrol","₹ 7,65,000"
57,Toyota,Fortuner,2017,7,"115,000 km",Automatic,second,Diesel,Nov-24,"Toyota Fortuner 2.8 2WD AT, 2017, Diesel","₹ 23,90,000"
59,Hyundai,Eon,2017,7,"27,000 km",Manual,second,Petrol,Oct-24,"Hyundai EON Era +, 2017, Petrol","₹ 3,00,000"
65,Mercedes-Benz,GLA Class,2018,6,"60,000 km",Automatic,second,Diesel,Nov-24,Mercedes-Benz GLA Class 2014-2017 200 CDI SPOR...,"₹ 14,50,000"
73,Honda,City,2016,8,"93,000 km",Automatic,second,Petrol,Nov-24,Honda City 2016 Petrol Good Condition,"₹ 5,75,000"
77,Hyundai,Creta,2015,9,"76,000 km",Automatic,second,Diesel,Nov-24,"Hyundai Creta 1.6 SX Automatic, 2015, Diesel","₹ 6,50,000"
97,Renault,Duster,2015,9,"150,000 km",Automatic,second,Diesel,Nov-24,"Renault Duster 2012-2015 4x4, 2015, Diesel","₹ 4,50,000"
104,Toyota,Camry,2015,9,"68,000 km",Automatic,second,Petrol,Nov-24,"Toyota Camry 2012-2014 Hybrid, 2015, Petrol","₹ 11,85,000"
133,Honda,City,2011,13,"74,000 km",Automatic,second,Petrol,Nov-24,"Honda City V Petrol CVT, 2011, Petrol","₹ 3,75,000"
138,Mahindra,XUV500,2017,7,"76,000 km",Automatic,second,Diesel,Nov-24,"Mahindra XUV500 W10 1.99 mHawk, 2017, Diesel","₹ 7,60,000"

In [35]:
# Check Target Variable
print(df["AskPrice"].head(20))

0        ₹ 1,95,000
1        ₹ 3,75,000
2        ₹ 1,84,999
3        ₹ 5,65,000
4        ₹ 6,85,000
5       ₹ 13,50,000
6       ₹ 10,25,000
7       ₹ 59,50,000
8        ₹ 6,22,000
9        ₹ 6,49,000
10       ₹ 3,95,000
11      ₹ 29,00,000
12       ₹ 2,40,000
13       ₹ 2,01,350
14    ₹ 1,18,00,000
15       ₹ 3,30,000
16      ₹ 10,45,000
17       ₹ 7,85,000
18       ₹ 5,55,000
19      ₹ 15,00,000
Name: AskPrice, dtype: str

In [36]:
# Check kmDriven
print(df["kmDriven"].sample(20, random_state=42))

13408     60,000 km
6472     130,000 km
9967      90,000 km
862       19,245 km
5967      43,369 km
12680     59,000 km
3017      88,000 km
3087      59,000 km
6375      65,000 km
2250     53000.0 km
542       98,525 km
6518      37,000 km
11721     45,000 km
12345     40,000 km
6702      59,000 km
6975      13,000 km
14454     72,000 km
13285     38,486 km
11311     78,300 km
6107      75,000 km
Name: kmDriven, dtype: str

In [37]:
# Check All Fuel Types
df["FuelType"].value_counts(dropna=False)

FuelType
Petrol        5822
Diesel        5239
hybrid        2012
Hybrid/CNG    1920
Name: count, dtype: int64

In [38]:
# Check Brands
sorted(df["Brand"].unique())

['Ambassador',
 'Ashok',
 'Aston Martin',
 'Audi',
 'BMW',
 'Bajaj',
 'Bentley',
 'Chevrolet',
 'Citroen',
 'Datsun',
 'Fiat',
 'Force',
 'Ford',
 'Honda',
 'Hummer',
 'Hyundai',
 'ICML',
 'Isuzu',
 'Jaguar',
 'Jeep',
 'Kia',
 'Lamborghini',
 'Land Rover',
 'Lexus',
 'MG',
 'Mahindra',
 'Maruti Suzuki',
 'Maserati',
 'Mercedes-Benz',
 'Mini',
 'Mitsubishi',
 'Nissan',
 'Opel',
 'Porsche',
 'Renault',
 'Rolls-Royce',
 'Skoda',
 'Ssangyong',
 'Tata',
 'Toyota',
 'Toyota Land',
 'Volkswagen',
 'Volvo']

In [39]:
# Check Models
df["model"].sample(30, random_state=42)

13408              Eeco
6472              Camry
9967               Polo
862               Swift
5967      Vitara-Brezza
12680               i20
3017               City
3087                GLS
6375             Ertiga
2250            TUV 300
542              Innova
6518        Swift-Dzire
11721          Fortuner
12345              Aura
6702               Brio
6975     Innova Hycross
14454           Wagon-R
13285               BRV
11311               Sx4
6107               Ritz
2312              Nexon
4991              Creta
1889               Nano
14051          S-Presso
169                Ciaz
1795             Tavera
14297           Celerio
3919                i20
7822               Ikon
3728              Rapid
Name: model, dtype: str

# Data Cleaning

In [41]:
# Remove Exact Duplicate Rows

print(f"Shape Before : {df.shape}")

duplicate_count = df.duplicated().sum()
print(f"Duplicate Rows : {duplicate_count}")

# Remove duplicates
df = df.drop_duplicates().reset_index(drop=True)

print(f"\nShape After : {df.shape}")

Shape Before : (14993, 11)
Duplicate Rows : 997

Shape After : (13996, 11)

In [42]:
# Clean AskPrice (Target Variable)

# Remove currency symbol, commas, and spaces
df["AskPrice"] = (
    df["AskPrice"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

# Convert to numeric
df["AskPrice"] = pd.to_numeric(df["AskPrice"], errors="coerce")

# Check results
print(df["AskPrice"].head())

print("\nData Type:")
print(df["AskPrice"].dtype)

print("\nMissing Values:")
print(df["AskPrice"].isnull().sum())

0    195000
1    375000
2    184999
3    565000
4    685000
Name: AskPrice, dtype: int64

Data Type:
int64

Missing Values:
0

In [44]:
# Clean kmDriven

# Remove "km", commas, and spaces
df["kmDriven"] = (
    df["kmDriven"]
    .str.replace("km", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

# Convert to numeric
df["kmDriven"] = pd.to_numeric(df["kmDriven"], errors="coerce")

# Check results
print(df["kmDriven"].head())

print("\nData Type:")
print(df["kmDriven"].dtype)

print("\nMissing Values:")
print(df["kmDriven"].isnull().sum())

0     98000.0
1    190000.0
2     77246.0
3     83500.0
4     45000.0
Name: kmDriven, dtype: float64

Data Type:
float64

Missing Values:
87

In [45]:
# Convert PostedDate to Datetime

df["PostedDate"] = pd.to_datetime(
    df["PostedDate"],
    format="%b-%y"
)

print(df["PostedDate"].head())

print("\nData Type:")
print(df["PostedDate"].dtype)

0   2024-11-01
1   2024-07-01
2   2024-11-01
3   2024-11-01
4   2024-11-01
Name: PostedDate, dtype: datetime64[us]

Data Type:
datetime64[us]

In [46]:
# Standardize FuelType

df["FuelType"] = df["FuelType"].replace({
    "hybrid": "Hybrid"
})

print(df["FuelType"].value_counts())

FuelType
Petrol        5398
Diesel        4846
Hybrid        1931
Hybrid/CNG    1821
Name: count, dtype: int64

In [47]:
# Check Cars with Very High Age

df[df["Age"] > 30][["Brand", "model", "Year", "Age", "AskPrice"]]

               Brand    model  Year  Age  AskPrice
1699        Mahindra     Jeep  1990   34    250000
6925   Maruti Suzuki      800  1986   38    120000
10498  Maruti Suzuki  Wagon-R  1931   93    349000
10624        Renault   Triber  1900  124    440000
10686       Mahindra     Jeep  1978   46    200000
11716  Maruti Suzuki    Swift  1920  104    519000

In [48]:
df[df["Year"] < 1950][
    ["Brand", "model", "Year", "Age", "AskPrice"]
]

               Brand    model  Year  Age  AskPrice
10498  Maruti Suzuki  Wagon-R  1931   93    349000
10624        Renault   Triber  1900  124    440000
11716  Maruti Suzuki    Swift  1920  104    519000

In [49]:
# Validate Age

current_year = 2024

age_check = df["Age"] == (current_year - df["Year"])

print("All Ages Correct:", age_check.all())

print("\nIncorrect Rows:")
print(df.loc[~age_check, ["Year", "Age"]].head())

All Ages Correct: True

Incorrect Rows:
Empty DataFrame
Columns: [Year, Age]
Index: []

In [50]:
# Remove Impossible Manufacturing Years

print("Shape Before:", df.shape)

df = df[df["Year"] >= 1950].reset_index(drop=True)

print("Shape After:", df.shape)

Shape Before: (13996, 11)
Shape After: (13993, 11)

In [54]:
# Final Data Quality Check

print("Dataset Shape:")
print(df.shape)

print("\n")


print("Missing Values:")
print("-"*20)
print(df.isnull().sum())

print("\n")


print("Duplicate Rows:")
print("-"*20)
print(df.duplicated().sum())

print("\n")


print("Data Types:")
print("-"*20)
print(df.dtypes)

Dataset Shape:
(13993, 11)


Missing Values:
--------------------
Brand            0
model            0
Year             0
Age              0
kmDriven        87
Transmission     0
Owner            0
FuelType         0
PostedDate       0
AdditionInfo     0
AskPrice         0
dtype: int64


Duplicate Rows:
--------------------
11


Data Types:
--------------------
Brand                      str
model                      str
Year                     int64
Age                      int64
kmDriven               float64
Transmission               str
Owner                      str
FuelType                   str
PostedDate      datetime64[us]
AdditionInfo               str
AskPrice                 int64
dtype: object

In [55]:
# Inspect Remaining Duplicate Rows

remaining_duplicates = df[df.duplicated(keep=False)]

print("Number of duplicate rows:", remaining_duplicates.shape[0])

remaining_duplicates.sort_values(by=list(df.columns)).head(20)

Number of duplicate rows: 22

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
7241,Honda,City ZX,2008,16,119000.0,Automatic,second,Hybrid/CNG,2024-11-01,"Honda City ZX GXi, 2008, CNG & Hybrids",145000
8803,Honda,City ZX,2008,16,119000.0,Automatic,second,Hybrid/CNG,2024-11-01,"Honda City ZX GXi, 2008, CNG & Hybrids",145000
6793,Hyundai,Verna,2013,11,90000.0,Manual,second,Diesel,2024-11-01,"Hyundai Verna 2011-2014 1.6 SX CRDi (O), 2013,...",529000
12375,Hyundai,Verna,2013,11,90000.0,Manual,second,Diesel,2024-11-01,"Hyundai Verna 2011-2014 1.6 SX CRDi (O), 2013,...",529000
3913,Hyundai,i20,2022,2,31851.0,Manual,first,Petrol,2024-08-01,"Hyundai i20 Magna Plus, 2022, Petrol",647000
11522,Hyundai,i20,2022,2,31851.0,Manual,first,Petrol,2024-08-01,"Hyundai i20 Magna Plus, 2022, Petrol",647000
3924,Kia,Sonet,2021,3,34000.0,Automatic,first,Hybrid/CNG,2024-08-01,"Kia Sonet HTK Plus Turbo DCT, 2021, CNG & Hybrids",899000
5451,Kia,Sonet,2021,3,34000.0,Automatic,first,Hybrid/CNG,2024-08-01,"Kia Sonet HTK Plus Turbo DCT, 2021, CNG & Hybrids",899000
4637,Mahindra,KUV 100,2017,7,75000.0,Manual,first,Diesel,2024-11-01,Mahindra KUV 100 2016-2017 mFALCON G80 K4 Plus...,435000
6052,Mahindra,KUV 100,2017,7,75000.0,Manual,first,Diesel,2024-11-01,Mahindra KUV 100 2016-2017 mFALCON G80 K4 Plus...,435000
372,Maruti Suzuki,Swift Dzire,2013,11,62000.0,Manual,second,Petrol,2024-11-01,"Maruti Suzuki Swift Dzire 1.2 Vxi BSIV, 2013, ...",350000
373,Maruti Suzuki,Swift Dzire,2013,11,62000.0,Manual,second,Petrol,2024-11-01,"Maruti Suzuki Swift Dzire 1.2 Vxi BSIV, 2013, ...",350000
3032,Mercedes-Benz,C-Class,2017,7,42000.0,Automatic,second,Petrol,2024-11-01,"Mercedes-Benz C-Class C 200, 2017, Petrol",2275000
8930,Mercedes-Benz,C-Class,2017,7,42000.0,Automatic,second,Petrol,2024-11-01,"Mercedes-Benz C-Class C 200, 2017, Petrol",2275000
6167,Mercedes-Benz,C-Class,2019,5,39000.0,Automatic,first,Diesel,2024-11-01,"Mercedes-Benz C-Class 2.0 220d Progressive, 20...",4350000
12687,Mercedes-Benz,C-Class,2019,5,39000.0,Automatic,first,Diesel,2024-11-01,"Mercedes-Benz C-Class 2.0 220d Progressive, 20...",4350000
7152,Tata,Tiago,2022,2,19300.0,Manual,first,Hybrid/CNG,2024-11-01,"Tata Tiago 1.2 Revotron XZ Plus CNG, 2022, CNG...",684000
8034,Tata,Tiago,2022,2,19300.0,Manual,first,Hybrid/CNG,2024-11-01,"Tata Tiago 1.2 Revotron XZ Plus CNG, 2022, CNG...",684000
1329,Toyota,Innova,2012,12,250000.0,Manual,second,Diesel,2024-11-01,"Toyota Innova 2.5 G (Diesel) 8 Seater, 2012, D...",799999
2553,Toyota,Innova,2012,12,250000.0,Manual,second,Diesel,2024-11-01,"Toyota Innova 2.5 G (Diesel) 8 Seater, 2012, D...",799999

In [56]:
# Remove Remaining Duplicate Rows

print("Shape Before:", df.shape)
print("Duplicate Rows:", df.duplicated().sum())

df = df.drop_duplicates().reset_index(drop=True)

print("\nShape After:", df.shape)
print("Duplicate Rows:", df.duplicated().sum())

Shape Before: (13993, 11)
Duplicate Rows: 11

Shape After: (13982, 11)
Duplicate Rows: 0

In [57]:
# Feature Extraction from PostedDate

df["Posted_Year"] = df["PostedDate"].dt.year
df["Posted_Month"] = df["PostedDate"].dt.month
df["Posted_Month_Name"] = df["PostedDate"].dt.month_name()

df[["PostedDate", "Posted_Year", "Posted_Month", "Posted_Month_Name"]].head()

  PostedDate  Posted_Year  Posted_Month Posted_Month_Name
0 2024-11-01         2024            11          November
1 2024-07-01         2024             7              July
2 2024-11-01         2024            11          November
3 2024-11-01         2024            11          November
4 2024-11-01         2024            11          November

In [58]:
# Save the Cleaned Dataset

df.to_csv("used_cars_clean.csv", index=False)
print("Cleaned Dataset Saved Successfully!")

Cleaned Dataset Saved Successfully!